Add support for resource `harbor_config_security`
goharbor/terraform-provider-harbor pull request #276
Opened 2022-11-28 10:58 UTC by naitmare01

This PR adds support for the resource `harbor_config_security` which should fix the issue https://github.com/goharbor/terraform-provider-harbor/issues/223. 

Please note that at the moment Harbor doesn't have any apis to remove the system-wide cve allow list.

2022-12-28 13:46 UTC, Vad1mo commented
thank you for your contribution, @naitmare01 do you have an idea how we can have an automated test setup?

2023-02-06 10:39 UTC, naitmare01 commented
We can probably write a test that performs all the supported operations on the list. E.g. update the list with strings of our choice. The textbox that stores all the cve-ids accept any strings really.

2023-05-31 14:47 UTC, flbla requested changes

2023-05-31 14:47 UTC, flbla commented on provider/resource_config_security.go
> +	body := SystemCVEAllowListBody(d)
```suggestion
	body := client.SystemCVEAllowListBody(d)
```

2023-05-31 14:47 UTC, flbla commented on provider/resource_config_security.go
> +	var jsonData SystemCveAllowListBodyPost
```suggestion
	var jsonData models.SystemCveAllowListBodyPost
```

2023-05-31 14:47 UTC, flbla commented on provider/resource_config_security.go
> +	body := SystemCVEAllowListBody(d)
```suggestion
	body := client.SystemCVEAllowListBody(d)
```

2023-05-31 14:47 UTC, flbla commented on provider/resource_config_security.go
> +	body := SystemCVEAllowListBody(d)
```suggestion
	body := client.SystemCVEAllowListBody(d)
```

2023-06-01 12:03 UTC, flbla requested changes

2023-06-01 12:03 UTC, flbla commented on provider/resource_config_security.go
> +		return fmt.Errorf("resource not found %s", d.Id())
```suggestion
		return fmt.Errorf("resource not found %s", models.PathSystemCVEAllowList)
```

2023-06-01 12:03 UTC, flbla commented on provider/resource_config_security.go
> +	stringid := fmt.Sprintf("%v", id)
```suggestion
```

2023-06-01 12:03 UTC, flbla commented on provider/resource_config_security.go
> +	d.SetId(stringid)
```suggestion
	d.SetId(models.PathSystemCVEAllowList)
```

2023-06-01 12:03 UTC, flbla commented on models/systemcve.go
> +	ID           int                     `json:"id,omitempty"`
```suggestion
	ID           string                  `json:"id,omitempty"`
```

2023-06-01 17:21 UTC, flbla commented on docs/resources/config_security.md
> +* `cve_allowlist` - (Optional) System allowlist. Vulnerabilities in this list will be ignored when pushing and pulling images. Should be in the format or `["CVE-123", "CVE-145"]` or `["CVE-123"]`
```suggestion
* `cve_allowlist` - (Required) System allowlist. Vulnerabilities in this list will be ignored when pushing and pulling images. Should be in the format or `["CVE-123", "CVE-145"]` or `["CVE-123"]`
```

2023-06-05 17:36 UTC, flbla commented on models/systemcve.go
> +	ID           string                  `json:"id,omitempty"`
```suggestion
	ID           int                     `json:"id,omitempty"`
```

2023-06-05 17:37 UTC, flbla commented on provider/resource_config_security.go
> +		return fmt.Errorf("resource not found %s", d.Id())
```suggestion
		return fmt.Errorf("resource not found %s", models.PathSystemCVEAllowList)
```

2023-06-05 17:38 UTC, flbla commented on provider/resource_config_security.go
> +	d.Set("creation_time", jsonData.CreationTime)
```suggestion
	// Convert the list of SystemCveAllowlistItems to a list of strings
	allowlistItems := make([]string, len(jsonData.Items))
	for i, item := range jsonData.Items {
		allowlistItems[i] = item.CveID
	}

	d.SetId(models.PathSystemCVEAllowList)
	d.Set("update_time", jsonData.UpdateTime)
	d.Set("expires_at", jsonData.ExpiresAt)
	d.Set("cve_allowlist", allowlistItems)
	d.Set("creation_time", jsonData.CreationTime)
```

2023-06-05 17:40 UTC, flbla commented on provider/resource_config_security.go
> +	body := client.SystemCVEAllowListBody(d)
```suggestion
func resourceConfigSecurityDelete(d *schema.ResourceData, m interface{}) error {
	apiClient := m.(*client.Client)
	d.Set("expires_at", nil)
	d.Set("cve_allowlist", []string{})
	body := client.SystemCVEAllowListBody(d)
```

2023-06-05 17:51 UTC, flbla requested changes

2023-06-05 17:51 UTC, flbla commented on provider/resource_config_security.go
> +}
```suggestion
func resourceConfigSecurityUpdate(d *schema.ResourceData, m interface{}) error {
	return resourceConfigSecurityCreate(d, m)
}

func resourceConfigSecurityDelete(d *schema.ResourceData, m interface{}) error {
	d.Set("expires_at", nil)
	d.Set("cve_allowlist", []string{})
	return resourceConfigSecurityCreate(d, m)
}
```

2023-06-05 18:04 UTC, merged